unit SchoolService_Impl;

// ----------------------------------------------------------------------
//  This file was automatically generated by Remoting SDK from a
//  RODL file downloaded from a server or associated with this project.
// 
//  Do not modify this file manually, or your changes will be lost when
//  it is regenerated the next time you update your RODL.
// ----------------------------------------------------------------------

{$I RemObjects.inc}

interface

uses
  {$IFDEF DELPHIXE2UP}System.SysUtils{$ELSE}SysUtils{$ENDIF},
  {$IFDEF DELPHIXE2UP}System.Classes{$ELSE}Classes{$ENDIF},
  {$IFDEF DELPHIXE2UP}System.TypInfo{$ELSE}TypInfo{$ENDIF},
  uROXMLIntf,
  uROClientIntf,
  uROClasses,
  uROTypes,
  uROServer,
  uROServerIntf,
  uROSessions,
  uRORemoteDataModule,
  SchoolLibrary_Intf;

type
  { Forward declarations }
  TSchoolService = class;

  TSchoolService = class(TRORemoteDataModule, ISchoolService)
  public
    function GetNameServer: UnicodeString; virtual;
    //function GetNameServer: AnsiString; virtual;
    function GetDateTimeServer: DateTime; virtual;
    function GetPupilsList(out aPupilsList: roPupilsView): Boolean; virtual;
  end;

implementation

{$IFDEF DELPHIXE2UP}
  {%CLASSGROUP 'System.Classes.TPersistent'}
{$ENDIF}
{$IFNDEF FPC}
  {$R *.dfm}
{$ENDIF}
{$IFDEF FPC}
  {$R *.lfm}
{$ENDIF}

uses
  uDBDataManager, SchoolLibrary_Invk;

var fClassFactory_SchoolService: IROClassFactory;

procedure Create_SchoolService(out anInstance: IInterface);
begin
  anInstance := TSchoolService.Create(nil);
end;

function TSchoolService.GetNameServer: UnicodeString;
begin
  result := 'SchoolService';
end;

function TSchoolService.GetPupilsList(out aPupilsList: roPupilsView): Boolean;
begin
  Result := DataManager.GetPupils(aPupilsList);
end;

function TSchoolService.GetDateTimeServer: DateTime;
begin
  Result := Now;
end;

initialization
  fClassFactory_SchoolService := TROClassFactory.Create('SchoolService', {$IFDEF FPC}@{$ENDIF}Create_SchoolService, TSchoolService_Invoker);
  // RegisterForZeroConf(fClassFactory_SchoolService, '_SchoolService_rosdk._tcp.');
finalization
  UnRegisterClassFactory(fClassFactory_SchoolService);
  fClassFactory_SchoolService := nil;
end.
